# Generated by Django 3.2.19 on 2023-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Выходной день в производственном календаре',
                'verbose_name_plural': 'Выходные дни в производственном календаре',
                'ordering': ('-off_date',),
            },
        ),
    ]
